// <auto-generated />
using Homework2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Homework2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("Homework2.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Latest smartphone",
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Wireless headphones",
                            Name = "Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Cotton t-shirt",
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Blue denim jeans",
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Bestselling novel",
                            Name = "Novel Book",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Delicious recipes",
                            Name = "Cookbook",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Complete garden tools",
                            Name = "Garden Tools Set",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Professional basketball",
                            Name = "Basketball",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Non-slip yoga mat",
                            Name = "Yoga Mat",
                            Price = 34.99m
                        });
                });

            modelBuilder.Entity("Homework2.Models.Product", b =>
                {
                    b.HasOne("Homework2.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
