// <auto-generated />
using System;
using Homework3.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Homework3.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Homework3.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2008, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "samanta.william@email.com",
                            FirstName = "Samanta",
                            Grade = "VII A",
                            LastName = "William",
                            ParentName = "Mana William",
                            PhoneNumber = "+1234567890",
                            StudentId = "#123456789"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2007, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "tony.soap@email.com",
                            FirstName = "Tony",
                            Grade = "VII B",
                            LastName = "Soap",
                            ParentName = "James Soap",
                            PhoneNumber = "+1234567891",
                            StudentId = "#123456789"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2008, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "karen.hope@email.com",
                            FirstName = "Karen",
                            Grade = "VII C",
                            LastName = "Hope",
                            ParentName = "Justin Hope",
                            PhoneNumber = "+1234567892",
                            StudentId = "#123456789"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2009, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "jordan.nico@email.com",
                            FirstName = "Jordan",
                            Grade = "VII A",
                            LastName = "Nico",
                            ParentName = "Amanda Nico",
                            PhoneNumber = "+1234567893",
                            StudentId = "#123456789"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2008, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "nadila.adja@email.com",
                            FirstName = "Nadila",
                            Grade = "VII A",
                            LastName = "Adja",
                            ParentName = "Jack Adja",
                            PhoneNumber = "+1234567894",
                            StudentId = "#123456789"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2007, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "johnny.ahmad@email.com",
                            FirstName = "Johnny",
                            Grade = "VII A",
                            LastName = "Ahmad",
                            ParentName = "Danny Ahmad",
                            PhoneNumber = "+1234567895",
                            StudentId = "#123456789"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2008, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Bandung",
                            Email = "alice.cooper@email.com",
                            FirstName = "Alice",
                            Grade = "VII B",
                            LastName = "Cooper",
                            ParentName = "David Cooper",
                            PhoneNumber = "+1234567896",
                            StudentId = "#123456790"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2007, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Surabaya",
                            Email = "michael.johnson@email.com",
                            FirstName = "Michael",
                            Grade = "VII C",
                            LastName = "Johnson",
                            ParentName = "Sarah Johnson",
                            PhoneNumber = "+1234567897",
                            StudentId = "#123456791"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2008, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "emily.brown@email.com",
                            FirstName = "Emily",
                            Grade = "VII A",
                            LastName = "Brown",
                            ParentName = "Robert Brown",
                            PhoneNumber = "+1234567898",
                            StudentId = "#123456792"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2009, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Medan",
                            Email = "david.martinez@email.com",
                            FirstName = "David",
                            Grade = "VII B",
                            LastName = "Martinez",
                            ParentName = "Lisa Martinez",
                            PhoneNumber = "+1234567899",
                            StudentId = "#123456793"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(2008, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "sarah.garcia@email.com",
                            FirstName = "Sarah",
                            Grade = "VII C",
                            LastName = "Garcia",
                            ParentName = "Carlos Garcia",
                            PhoneNumber = "+1234567800",
                            StudentId = "#123456794"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2007, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Semarang",
                            Email = "james.wilson@email.com",
                            FirstName = "James",
                            Grade = "VII A",
                            LastName = "Wilson",
                            ParentName = "Patricia Wilson",
                            PhoneNumber = "+1234567801",
                            StudentId = "#123456795"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(2008, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "jessica.anderson@email.com",
                            FirstName = "Jessica",
                            Grade = "VII B",
                            LastName = "Anderson",
                            ParentName = "Mark Anderson",
                            PhoneNumber = "+1234567802",
                            StudentId = "#123456796"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2009, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Yogyakarta",
                            Email = "daniel.taylor@email.com",
                            FirstName = "Daniel",
                            Grade = "VII C",
                            LastName = "Taylor",
                            ParentName = "Nancy Taylor",
                            PhoneNumber = "+1234567803",
                            StudentId = "#123456797"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2008, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Jakarta",
                            Email = "laura.thomas@email.com",
                            FirstName = "Laura",
                            Grade = "VII A",
                            LastName = "Thomas",
                            ParentName = "Steven Thomas",
                            PhoneNumber = "+1234567804",
                            StudentId = "#123456798"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
